# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_readPLY <- function(filename, verbose) {
    .Call('Rply_cpp_readPLY', PACKAGE = 'Rply', filename, verbose)
}

